clc; close all; clear all;
DataDir = fullfile(pwd, 'cloud_mov.pcd');
cloud_mov = pcread(DataDir);
cloud_mov = pcdownsample(cloud_mov, 'random', 2000 / length(cloud_mov.Location)); 
DataDir = fullfile(pwd, 'cloud_ref.pcd');
cloud_ref = pcread(DataDir);
Tf0 = eye(4);
params = genParamsFun(cloud_mov, cloud_ref, ...
    'P', [1.0 2.0], ...
    'Tf0', Tf0, ...
    'mode', 'point2plane', ...
    'is_show', 1, ...
    'verbose', 1);
outParams = MoEFun(params)